### ISSUE TITLE
Crash after uploading a file into ownDrop

### ISSUE THREAD

**Issue by ElyFornoville** [Leandros/ownDrop#21] opened 2014-09-25 12:24 UTC
When I upload a file it crashed after uploading the file and retrieving the URL.
File attached.
![schermafbeelding 2014-09-25 om 14 23 52](https://cloud.githubusercontent.com/assets/8914684/4404244/eaa9101e-44ae-11e4-9d96-01f2dec7882f.png)

Is there any fix for this?

Thanks.
Regards,
Ely

**Comment by Leandros** [comment] 2014-09-25 12:32
It's a duplicate of #18. It has been fixed a few days ago, I'll publish an update tomorrow evening, since I don't have my keys here at works.

**Comment by ElyFornoville** [comment] 2014-10-02 13:16
Thank  you!
Do you have any idea when this update will be published?

**Comment by Leandros** [comment] 2014-10-02 21:44
Sorry, I've totally missed this! My biggest apologies. The update is published!

**Comment by ElyFornoville** [comment] 2014-10-03 07:23
Thank you.
But the crash is still there.

I upload something.
It still crashes when I try to select the file to create the download link.
Also the download link is a URL that uses and old server setting I entered the first time I used the app.
I changed de server address but the created links still use the old one.

Regards,
Ely

**Comment by Leandros** [comment] 2014-10-03 12:57
Please completely uninstall it once, with an application like [AppCleaner](http://www.freemacsoft.net/appcleaner/) and install the newest version again. Enter all your settings and try to use it. 
If it crashes again, please get me the crash log.

**Comment by Leandros** [comment] 2014-10-03 13:39
Fixed in 0.8.0. Just update it.

**Closed as completed by Leandros** 2014-10-03 13:40 UTC
Labels: duplicate

**Comment by ElyFornoville** [comment] 2014-10-03 13:50
Thank you.
All seems to work perfect now!
